### ISSUE TITLE
How to install?

### ISSUE THREAD

**Issue by jakobroehrl** [cwilby/nextcloud-automatic-media-encoder#4]
Hi,
nice app, thanks a lot.
How to install it? Will it be published into the app store?
Would it be possible to add an admin setting, that allow all uploaded media to be encoded?
Thanks!

**Comment by cwilby** [comment]
Just working on admin/personal settings now.

Admins will be able to configure global settings (looking to make a resource usage slider)

Users will be able to click a "Convert Existing Media" button to kick off jobs for all non converted media.

You are better using https://GitHub.com/cwilby/nextcloud-workflow-media-converter.  This is an older version where I built the workflow engine manually... before realizing Nextcloud had one built in 🤦‍♂️

If there are other features you would want to see please post an issue there.  (Now is a good time as I'm just getting things ready to release)

**Comment by jakobroehrl** [comment]
Do you have an idea when you could publish it?
Can't install it for testing.
Cloning the repo or downloading the master.zip into my apps Folder doesn't work out. Can't activate it afterwards.

**Comment by cwilby** [comment]
Just doing QA on it now for initial release.  Next 2 weeks worst case, tonight best case.

**Comment by cwilby** [comment]
@jakobroehrl  This has now been released to the app store: https://apps.nextcloud.com/apps/workflow_media_converter

**Comment by jakobroehrl** [comment]
Saw it, thanks. I will test it!
Very happy that this app could maybe replace my scriptings

**Comment by cwilby** [comment]
Also not a bad estimate ¯\_(ツ)_/¯
